### ISSUE TITLE
[BUG] Breaking changes should not be released in minor releases

### ISSUE THREAD

**Issue by hakimio** [cap-js/cds-types#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Version `0.4.0` was released with major breaking changes and broke all libraries depending on `^0.2.0` or in case of `@sap/cds` depending on `<1`.

### Expected Behavior

Breaking changes should be released only in major releases. `v0` should be fixed by releasing `0.4.1` with old types.

### References

https://en.wikipedia.org/wiki/Software_versioning#Semantic_versioning

### Versions

| Library            | Version                             |
| ---------------------- | ---------------------------------------------------------- |
| @cap-js/cds-typer      | 0.22.0                                                     |
| @cap-js/cds-types      | 0.2.0                                                      |
| @cap-js/postgres       | 1.8.0                                                      |
| @sap/cds               | 7.9.2                                                      |
| @sap/cds-compiler      | 4.9.4                                                      |
| @sap/cds-dk            | 7.9.3                                                      |
| @sap/cds-dk (global)   | 7.9.2                                                      |
| @sap/cds-fiori         | 1.2.3                                                      |
| @sap/cds-foss          | 5.0.0                                                      |
| @sap/cds-mtxs          | 1.18.1                                                     |
| @sap/eslint-plugin-cds | 3.0.4                                                      |
| Node.js                | v20.13.1                                                   |

**Comment by daogrady** [comment]
Hi Tomas,

thank you for bringing our attention to this. Packages with major number 0 actually have a bit of a special semantic and do not withstand breaking changes wrt changes in minor or patch numbers (quoting from your link: "The presence of a pre-release tag (-alpha, -beta) indicates substantial risk, as does a major number of zero (0.y.z), which is used to indicate a work-in-progress that may contain any level of potentially breaking changes (highest risk)").

Regardless, can you point out the specific cases that broke for you? Is pinning the version to 0.2.0 an option for you?

Best,
Daniel

**Comment by hakimio** [comment]
While yes, I can personally pin the `cds-types` version, but you are breaking other TS apps and libs (ie `cds-ts-dispatcher`) which depend on `@sap/cds` `v7` which in-turn re-exports your types. 
Why is a stable version of `@sap/cds` re-exporting types from unstable `cds-types` and why doesn't `@sap/cds` pin the types dependency to one specific version or better yet, declare the types internally instead of depending on unstable 3rd party community maintained package?

In general, I find the choice to only release `0.x` versions and use that as an excuse for releasing breaking changes in minor releases "odd" to say the least. Maybe you should put a warning somewhere saying that production code should not use `cds-types` and `cds-typer` since they are unstable/experimental/alpha packages and breaking changes in minor releases are expected?

**Comment by daogrady** [comment]
> Maybe you should put a warning somewhere saying that [...] breaking changes in minor releases are expected?

that is implicit by the 0.y.z version number.

> declare the types internally instead of depending on unstable 3rd party community maintained package?

we did do that before, but as we are aiming to make all components we can open source, cds-types was a natural fit. It was formerly rather inconvenient for users to have to open an internal issue for us to fix issues. They now at least have the possibility to take them on themselves, if they wish to do so.

> and why doesn't @sap/cds pin the types dependency to one specific version

because that would require a new release of `@sap/cds` with a newly pinned version of `@cap-js/cds-types` for every release of the latter, which is currently not feasible. I will discuss the possibility of at least defining a closed range for the cds-types dependency to exclude breaking changes internally. Thanks for the suggestion.

**Comment by hakimio** [comment]
What's currently preventing you from releasing a stable release? Do you have any roadmap for stable release?

**Comment by daogrady** [comment]
Yes, we do, but without fixed dates attached to it. We are currently working on getting cds-types into a state where it matches up with the implementation (which it currently does not in all regards, hence the need for breaking changes and is the reason why we have not done a stable release yet). We then want to implement mechanisms to lessen the chance of changes in the implementation unknowingly diverging from the types. That's when we have reached a stable state which we can release as 1.0.0.

cds-types introducing breaking changes within version 0.y.z is fine, but the problem (which you also pointed out) is that due to how it is currently used within cds, it will cause transitive breaks. I will bring this up in the relevant syncs, but this is something that has to be done in the `@sap/cds` package.

**Comment by hakimio** [comment]
Have you considered converting at least the public `@sap/cds` code parts to TypeScript or using `JSDoc` to automatically generate the TS types and make sure they are always in sync? Having all types in manually updated 3rd party library you will always have a significant risk of breaking consumer TS code.

**Comment by daogrady** [comment]
Yes, that was considered. The options have been weighed by the persons responsible for strategic decisions and they determined the .d.ts approach to be the most feasible for our scenario.
As this is the current mode we have to operate in, we are doing our best to keep types and implementation in sync as much as possible through additional mechanisms in our internal CI and added testing in the libs.

**Comment by daogrady** [comment]
We discussed the matter today and the problem likely stemmed from 0.4.0 briefly being incorrectly flagged as `latest` on npmjs. It has since been flagged as `next` instead, so new projects should still install the most recent `latest` version (0.2.0) which does not contain the breaking changes introduced in 0.4.0. So everything should work fine except for projects that had been initialised in the brief window the tag was incorrect. Sorry for any convenience this may have caused.
We will have internal follow-ups about the ongoing version numbering of cds-types and a possible stable 1.0.0 release.

**Comment by dragolea** [comment]
Hi @daogrady 

I feel @hakimio in this case.

I am using `cds-typer` for a year already, probably I started using sice version `0.11.0`.

In one year timelaps it should be already at least version `1.0.0`, this doesn't mean to be perfect stable, but at least to follow npm conventions and alert the devs which use that package.

**Comment by daogrady** [comment]
Hi Daniel,

thanks for weighing in on this. Don't worry, we are aware of the pain this is causing. We do aim for a 1.0.0 release which we wanted to losely couple with cds8. The latter is now out the door and we are in the middle of the fixes that are to be expected with any larger release. After that we can approach the last remaining features and cleanups we believe should be part of a full release and then hope to go for 1.0.0 in a timely manner.

Best,
Daniel

P.S.: seeing that you mentioned cds-typer, this statement is meant for _cds-types_ for now. cds-typer has still many gaps and missing features that puts it much further away from a proper release than cds-types.

**Comment by hakimio** [comment]
@daogrady `cds-types v0.6.1` has been released yet again as stable and is breaking `cds v7` again...

**Comment by daogrady** [comment]
cds-types 0.6 is to be used with cds 8. Could you please share your project setup that led to the use of cds-types 0.6 + cds 7?

**Comment by hakimio** [comment]
Try `npm i @sap/cds@7` in a new project and see which version of `cds-types` is installed. Same issue as before.
There shouldn't be any more `cds-types` `0.x` releases since you'll keep breaking `cds v7` projects. Instead you can just release `v1.x-alpha` and add `cds-types` as `optional peer-dependency` to `cds v8`.
