### ISSUE TITLE
[BUG] Attributes have value or null or undefined, even if they are defined in the schema as mandatory

### ISSUE THREAD

**Issue by Markus-Schroeder-de** [cap-js/cds-types#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

if cds_types are created from the CDS-Schema, even fields which are mandatory or aspects, as ID or managed, the attributes in the types are optional. even i don't get it, why all attributes are optional, even if they have defined a default value in the schema, or why functions give back an type or undefined or null.

### Expected Behavior

1. mandatory fields or if they have a default value, should not typed as optional
2. functions should avoid to return undefined or null instead of a type

### References

1. Clean Code from Robert C. Martin: “Functions should either return a meaningful result or throw an exception, but never null.”
2. official typeScript Documentation: Avoid using null and undefined unless absolutely necessary.

### Versions

@cap-js/asyncapi: 1.0.2
@cap-js/cds-typer: 0.30.0
@cap-js/cds-types: 0.8.0
@cap-js/db-service: 1.16.0
@cap-js/openapi: 1.0.7
@cap-js/sqlite: 1.7.7
@sap/cds: 8.5.0
@sap/cds-compiler: 5.3.2
@sap/cds-dk: 8.5.0
@sap/cds-dk (global): 8.5.0
@sap/cds-fiori: 1.2.7
@sap/cds-foss: 5.0.1
@sap/cds-mtxs: 2.4.0
@sap/eslint-plugin-cds: 3.1.2
Node.js: v20.17.0

**Comment by daogrady** [comment]
Hi Markus,

thank you for your question.
Regarding the optionality of properties, I'd like to point you to [the appropriate section in CAPire](https://cap.cloud.sap/docs/tools/cds-typer#handling-optional-properties) where we explain how this reflects reality and propose a few approaches to handling this. Please note that optional (`?:`) is different from `null` or `undefined` [wrt to checks like `in`](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBCBGArAXDA3jAHqsBXAtvAKYBOMAPjLmACZEBmAlmETQDQwCeA-DgcWQC+MALzosqanSYsaMQQCgFoSCAA2RAHRqQAcwAUAckyGYzOEgCUy8BHVadBw51PmEiS0A), where it means "the key is just not present at all".

I was not able to locate the section of the TypeScript documentation you referred to. But as you cited Uncle Bob, I would like to point out that when "Clean Code" was released in 2009, there was no optional chaining (`?.`) et al. and he specifically points out the pitfall of _forgetting_ null checks

> All it takes is one missing null check to send an application
spinning out of control. Did you notice the fact that there wasn’t a null check in the second line of that nested
if statement? What would have happened at runtime if persistentStore were null? We
would have had a NullPointerException at runtime, and either someone is catching
NullPointerException at the top level or they are not. [...]

_Clean Code_, Robert C. Martin, 2009

TypeScript explicitly [_forces_ you](https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABMJAKAHgLkWEBbAIwFMAnRAHxxABtqBKbXQ0xAbwChEvESioQSSdADoocAKLoADgiJhYAQ2qo67AL5A) to do each required null check and to narrow the type down enough to be sure each operation you are attempting to execute is in fact valid. So while `null` needs special care, I don't think it is as nefarious as it used to be, due to the tools we have at out disposal nowadays.

I will bring up fields that are marked as mandatory in the next type sync to see if they should be exempt from being tagged as optional.

Best,
Daniel

**Comment by Markus-Schroeder-de** [comment]
Thank you very much for your answer. If I had thought about it a little longer, I would have understood why it is like that. I can do a select and, for example, only fetch the first name and last name of persons. Then the mandatory required fields externalUserId, etc. would not be in the response and I would have again a problem. sigh.  Sorry, I was a bit upset after I upgraded to eslint9 and enabled strict-null-checks and am constantly being chased around the office with a physical copy of "Clean Code".

Best,
Markus

**Comment by daogrady** [comment]
Hi Markus,

no worries, this is a common question and we are aware of the confusion it sometimes causes. We will continue to monitor the situation and see if we can provide better solutions over time. 🙂

Best,
Daniel
